import React from 'react';
import { ActivityIndicator, Platform, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { MaterialIcons } from '@expo/vector-icons';
import { tokens } from './tokens';

export function Page({ children, style, contentStyle }) { return <View style={[styles.page, style]}><View style={[styles.content, contentStyle]}>{children}</View></View>; }
export function PageHeader({ eyebrow, title, subtitle, action, meta }) { return <View style={styles.header}><View style={{ flex: 1 }}>{eyebrow ? <Text style={styles.eyebrow}>{eyebrow}</Text> : null}<Text style={styles.h1}>{title}</Text>{subtitle ? <Text style={styles.subtitle}>{subtitle}</Text> : null}{meta ? <View style={styles.metaRow}>{meta}</View> : null}</View>{action ? <View style={styles.headerAction}>{action}</View> : null}</View>; }
export function Card({ children, style, padded = true }) { return <View style={[styles.card, padded && styles.cardPadded, style]}>{children}</View>; }
export function Button({ children, variant = 'primary', icon, loading, style, textStyle, disabled, ...props }) { const variantStyle = variant === 'secondary' ? styles.btnSecondary : variant === 'ghost' ? styles.btnGhost : styles.btnPrimary; const variantText = variant === 'primary' ? styles.btnTextPrimary : styles.btnTextDark; return <TouchableOpacity {...props} disabled={disabled || loading} style={[styles.btn, variantStyle, (disabled || loading) && styles.disabled, style]}>{loading ? <ActivityIndicator color={variant === 'primary' ? '#fff' : tokens.color.brand} /> : icon ? <MaterialIcons name={icon} size={18} color={variant === 'primary' ? '#fff' : tokens.color.brand} /> : null}{!loading ? <Text style={[styles.btnText, variantText, textStyle]}>{children}</Text> : null}</TouchableOpacity>; }
export function Badge({ children, tone = 'brand', style }) { const toneStyle = tone === 'green' ? styles.badgeGreen : tone === 'red' ? styles.badgeRed : tone === 'amber' ? styles.badgeAmber : styles.badgeBrand; return <View style={[styles.badge, toneStyle, style]}><Text style={styles.badgeText}>{children}</Text></View>; }
export function Field({ label, error, icon, style, inputStyle, ...props }) { return <View style={[styles.field, style]}>{label ? <Text style={styles.label}>{label}</Text> : null}<View style={[styles.inputShell, error && styles.inputError]}>{icon ? <MaterialIcons name={icon} size={18} color={tokens.color.faint} /> : null}<TextInput placeholderTextColor={tokens.color.faint} style={[styles.input, inputStyle]} {...props} /></View>{error ? <Text style={styles.error}>{error}</Text> : null}</View>; }
export function EmptyState({ icon = 'inbox', title, message, action }) { return <Card style={styles.empty}><View style={styles.emptyIcon}><MaterialIcons name={icon} size={26} color={tokens.color.brand} /></View><Text style={styles.emptyTitle}>{title}</Text>{message ? <Text style={styles.emptyText}>{message}</Text> : null}{action ? <View style={{ marginTop: 16 }}>{action}</View> : null}</Card>; }
export function Metric({ label, value, tone = 'brand' }) { return <Card style={styles.metric}><Badge tone={tone}>{label}</Badge><Text style={styles.metricValue}>{value}</Text></Card>; }

const webShadow = Platform.OS === 'web' ? { boxShadow: tokens.shadow.card } : { shadowColor: '#0F172A', shadowOpacity: 0.08, shadowRadius: 20, shadowOffset: { width: 0, height: 10 }, elevation: 3 };
const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: tokens.color.page }, content: { width: '100%', maxWidth: tokens.maxWidth, alignSelf: 'center', padding: 24, gap: 18 },
  header: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 18, marginBottom: 4, flexWrap: 'wrap' }, eyebrow: { color: tokens.color.brand, fontWeight: '900', letterSpacing: 1.2, textTransform: 'uppercase', fontSize: 12, marginBottom: 8 }, h1: { color: tokens.color.ink, fontSize: 42, lineHeight: 48, fontWeight: '900' }, subtitle: { color: tokens.color.muted, marginTop: 10, fontSize: 16, lineHeight: 24, maxWidth: 720 }, metaRow: { flexDirection: 'row', gap: 8, marginTop: 12, flexWrap: 'wrap' }, headerAction: { alignItems: 'flex-end' },
  card: { backgroundColor: tokens.color.panel, borderWidth: 1, borderColor: tokens.color.line, borderRadius: tokens.radius.lg, ...webShadow }, cardPadded: { padding: 22 },
  btn: { minHeight: 46, borderRadius: tokens.radius.md, paddingHorizontal: 18, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 }, btnPrimary: { backgroundColor: tokens.color.brand }, btnSecondary: { backgroundColor: tokens.color.brandSoft, borderWidth: 1, borderColor: '#C7D2FE' }, btnGhost: { backgroundColor: 'transparent' }, btnText: { fontWeight: '900' }, btnTextPrimary: { color: '#fff' }, btnTextDark: { color: tokens.color.brandDark }, disabled: { opacity: 0.55 },
  badge: { alignSelf: 'flex-start', borderRadius: tokens.radius.pill, paddingHorizontal: 10, paddingVertical: 5 }, badgeBrand: { backgroundColor: tokens.color.brandSoft }, badgeGreen: { backgroundColor: '#DCFCE7' }, badgeRed: { backgroundColor: '#FEE2E2' }, badgeAmber: { backgroundColor: '#FEF3C7' }, badgeText: { color: tokens.color.ink, fontSize: 12, fontWeight: '900' },
  field: { gap: 7 }, label: { color: tokens.color.ink, fontWeight: '800' }, inputShell: { minHeight: 52, borderRadius: tokens.radius.md, borderWidth: 1, borderColor: '#CBD5E1', backgroundColor: '#fff', flexDirection: 'row', alignItems: 'center', gap: 9, paddingHorizontal: 14 }, inputError: { borderColor: tokens.color.red, backgroundColor: '#FEF2F2' }, input: { flex: 1, color: tokens.color.ink, fontWeight: '700', outlineStyle: 'none' }, error: { color: '#DC2626', fontWeight: '700', fontSize: 12 },
  empty: { alignItems: 'center', padding: 32 }, emptyIcon: { width: 56, height: 56, borderRadius: 18, backgroundColor: tokens.color.brandSoft, alignItems: 'center', justifyContent: 'center', marginBottom: 14 }, emptyTitle: { color: tokens.color.ink, fontSize: 20, fontWeight: '900', textAlign: 'center' }, emptyText: { color: tokens.color.muted, marginTop: 8, textAlign: 'center', lineHeight: 21 }, metric: { padding: 16, minWidth: 150, gap: 12 }, metricValue: { fontSize: 28, fontWeight: '900', color: tokens.color.ink },
});
